version: 0.2

phases:
  install:
    commands:
      - yum install httpd -y
  pre_build:
    commands:
      - echo "Starting tests..."
      - make test
  build:
    commands:
      - echo "Starting build..."
      - make all-variants
  post_build:
    commands:
      - echo "Build completed on $(date)"
artifacts:
  files:
      - '**/*'
  base-directory: 'bin'
